- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server-core-5.5
    - mysql-client-core-5.5
    - libmysqlclient-dev
    - python-mysqldb
    - mysql-server
    - mysql-client

- name: Start the MySQL service
  service:
    name: mysql
    state: started

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create deploy user for MySQL
  mysql_user:
    name: deploy
    host: "%"
    password: root
    priv: "*.*:ALL,GRANT"

- name: Ensure anonymous users are not in the database
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
  loop:
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template:
    src: templates/.my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    mode: "0600"

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: root
  loop:
    - 127.0.0.1
    - ::1
    - localhost
