---
# Lancer un conteneur MySQL avec les paramètres de connexion
- name: Run MySQL container
  docker_container:
    name: mysql-container
    image: mysql:latest
    state: started
    restart_policy: always
    exposed_ports:
      - "3306"
    published_ports:
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

# Créer un volume Docker pour persister les données de la base de données
- name: Create a persistent volume for MySQL data
  docker_volume:
    name: mysql-data
    state: present
